# Generated by Django 3.1.14 on 2021-12-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(max_length=100)),
                ('info_image', models.ImageField(upload_to='')),
                ('info_description', models.CharField(max_length=200)),
                ('date_of_pub', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
