# Generated by Django 3.1.14 on 2021-12-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
